Create auth page
raulbanut/LocateApp pull request #1
Opened 2022-09-12 12:30 UTC by raulbanut

2022-09-12 14:16 UTC, sergiu-corbu commented on Locate/Locate/ContentView.swift
> +                        .navigationTitle("Log In")
nav tite ar trebui setat direct in register view

2022-09-12 14:18 UTC, sergiu-corbu commented on Locate/Locate/Coordinator.swift
> +enum Destinations: Hashable {
aici as denumi ViewDestinations / NavigationDestination

2022-09-12 14:18 UTC, sergiu-corbu commented on Locate/Locate/Coordinator.swift
> +
asta vrei sa fie private(set) ca sa nu ti l poata modifica nimeni din exterior, decat prin metodele pe care le vei scrie tu

2022-09-12 14:20 UTC, sergiu-corbu commented on Locate/Locate/Coordinator.swift
> +    }
as numi functia pushView, apoi ai nevoie de  popView

2022-09-12 14:20 UTC, sergiu-corbu commented on Locate/Locate/CustomViews/ButtonView.swift
> +    let callback: () -> Void
let action

2022-09-12 14:21 UTC, sergiu-corbu commented on Locate/Locate/CustomViews/ButtonView.swift
> +                Spacer()
daca vrei ca textul sa fie centrat pe mijloc, pune `.frame(maxWidth: .infinity) `si scapi de spacere

2022-09-12 14:22 UTC, sergiu-corbu commented on Locate/Locate/CustomViews/ButtonView.swift
> +struct ButtonView: View {
button view e prea abstract. PrimaryButton / MainButton de ex

2022-09-12 14:23 UTC, sergiu-corbu commented on Locate/Locate/CustomViews/LoadingView.swift
> +    func `repeat`(while expression: Bool, autoreverses: Bool = true) -> Animation {
asta nu prea isi are sensul. nu te ajuta cu mare lucru, parerea mea

2022-09-12 14:23 UTC, sergiu-corbu commented on Locate/Locate/CustomViews/Shapes/BackgroundBody.swift
> +struct BackgroundBody: Shape {
view ul asta are vreo utilitate? e un path gol

2022-09-12 14:24 UTC, sergiu-corbu commented on Locate/Locate/CustomViews/TextFieldView.swift
> +
astea le poti scrie mai usor: text: String si type: FieldType

2022-09-12 14:27 UTC, sergiu-corbu commented on Locate/Locate/Screens/Authentication/Terms+AlreadyAccountView.swift
> +            Text(registerButtonIsPresent ? "Create a new account? Sign up." : "Already have an account? Log in.")
textele ar trebui tinute intr un obiect Texts si intr un NSLocalizedString. iti arat mai tarziu la ce ma refer

2022-09-12 14:28 UTC, sergiu-corbu commented on Locate/Locate/Screens/Authentication/AuthenticationView.swift
> +            if buttonIsPressed { LoadingView() }
pe loading view ai putea pune o tranzitie, sa zicem .opacity.animation(.easeOut)

2022-09-12 14:30 UTC, sergiu-corbu requested changes
.

2022-09-12 14:30 UTC, sergiu-corbu commented on Locate/Locate/Screens/Authentication/Terms+AlreadyAccountView.swift
> +            .previewDevice("iPhone SE (3rd generation)")
tine ti preview devices undeva si scrie doar o singura data numele asta hardcodat

2022-09-17 17:43 UTC, raulbanut commented on Locate/Locate/CustomViews/LoadingView.swift
> +    func `repeat`(while expression: Bool, autoreverses: Bool = true) -> Animation {
pai altfel nu se face animatia aia de la loading :))

2022-09-17 17:45 UTC, raulbanut commented on Locate/Locate/CustomViews/Shapes/BackgroundBody.swift
> +struct BackgroundBody: Shape {
asta e background-ul.. nu am o img pentru el

2022-10-03 20:07 UTC, merged